swagger: "2.0"
info:
  description: "An API to retrieve system data from database"
  version: "1.0.0"
  title: "SRE Data Service"
  contact:
    email: "zayyansmatin@gmail.com"
tags:
- name: "timeseries"
  description: "retrieve timeseries of CPU and concurrency data"
- name: "statistic"
  description: "retrieve average, maximum and minimum of specified resource"
schemes:
- "https"
paths:
  /timeseries:
    get:
      tags:
      - "timeseries"
      summary: "retrieve cpu and concurrency timeseries in requested period"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/Timeseries'
        "500":
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Message'
  /statistic/cpu:
    get:
      tags:
      - "statistic"
      summary: "retrieve cpu statistics in requested period"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/Statistic'
        "500":
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Message'
  /statistic/concurrency:
    get:
      tags:
      - "statistic"
      summary: "retrieve concurrency statistics in requested period"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: '#/definitions/Statistic'
        "500":
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/Message'
definitions:
  Timeseries:
    properties:
      timestamp:
        type: integer
      cpu:
        type: number
      concurrency:
        type: integer 
  Statistic:
    properties:
      avg:
        type: number
      max:
        type: number
      min:
        type: number
  Message:
    properties:
      error:
        type: string
