swagger: "2.0"
info:
  description: "An API to retrieve system data from database"
  version: "1.0.0"
  title: "SRE Data Service"
  contact:
    email: "zayyansmatin@gmail.com"
tags:
- name: "timeseries"
  description: "retrieve timeseries of CPU and concurrency data"
- name: "statistic"
  description: "retrieve average, maximum and minimum of specified resource"
schemes:
- "https"
paths:
  /timeseries:
    get:
      tags:
      - "timeseries"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid request"
          schema:
            type: "string"
  /statistic/cpu:
    get:
      tags:
      - "statistic"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid request"
          schema:
            type: "string"
  /statistic/concurrency:
    get:
      tags:
      - "statistic"
      summary: "Logs out current logged in user session"
      produces:
      - "application/json"
      parameters:
      - name: "startTime"
        in: "query"
        required: true
        type: "integer"
      - name: "endTime"
        in: "query"
        required: true
        type: "integer"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid request"
          schema:
            type: "string"
  